### ISSUE TITLE
[需求]增加日志查看器

### ISSUE THREAD

**Issue by 599316527** [chestnutchen/lego-sdk-tool#12]
不确定这功能放在这个扩展里是否合适，先讨论下

日志有两种：

1. 写死的，遍历 DOM 的 title2 就能拿到的
2. JS 动态发送的

对于第一种，遍历一下展现出来应该没什么问题；第二种就要监听网络，从特定规则的请求中取

可行么？

**Comment by chestnutchen** [comment]
没看懂需求。。

**Comment by 599316527** [comment]
新做一个扩展

基本功能：
1. page action 页面右侧出一个窗口
2. 监听网络，根据 url 规则提取发送的统计日志
3. 统计日志显示在右侧窗口中，包含 linkName 和 materialName/id
4. 日志正文分 linkName 和 xpath，如果出现两者相同的，则此条记录背景变红警告

高级功能：
1. 有的日志没有 xpath，需要监控点击，然后根据点击target来算出 xpath
2. 鼠标 hover 右侧窗口内记录，高亮对应的 xpath 节点

![sample](http://ww2.sinaimg.cn/large/661b7679jw1eymsg8q0rrj2085060aa4.jpg)
